defmodule Zorcle.MascotGame.Questions do
  def get_questions do
    [
      %{school: "Abilene Christian University", mascot: "Wildcats"},
      %{school: "University of Akron", mascot: "Zips"},
      %{school: "University of Alabama", mascot: "Crimson Tide"},
      %{school: "Alabama Agricultural and Mechanical University", mascot: "Bulldogs"},
      %{school: "University of Alabama at Birmingham", mascot: "Blazers"},
      %{school: "Alabama State University", mascot: "Hornets"},
      %{school: "University at Albany, SUNY", mascot: "Great Danes"},
      %{school: "Alcorn State University", mascot: "Braves"},
      %{school: "American University", mascot: "Eagles"},
      %{school: "Appalachian State University", mascot: "Mountaineers"},
      %{school: "University of Arizona", mascot: "Wildcats"},
      %{school: "Arizona State University", mascot: "Sun Devils"},
      %{school: "University of Arkansas", mascot: "Razorbacks"},
      %{school: "University of Arkansas at Little Rock", mascot: "Trojans"},
      %{school: "University of Arkansas at Pine Bluff", mascot: "Golden Lions"},
      %{school: "Arkansas State University", mascot: "Red Wolves"},
      %{school: "Auburn University", mascot: "Tigers"},
      %{school: "Austin Peay State University", mascot: "Governors"},
      %{school: "Ball State University", mascot: "Cardinals"},
      %{school: "Baylor University", mascot: "Bears"},
      %{school: "Belmont University", mascot: "Bruins"},
      %{school: "Bethune-Cookman University", mascot: "Wildcats"},
      %{school: "Binghamton University", mascot: "Bearcats"},
      %{school: "Boise State University", mascot: "Broncos"},
      %{school: "Boston College", mascot: "Eagles"},
      %{school: "Boston University", mascot: "Terriers"},
      %{school: "Bowling Green State University", mascot: "Falcons"},
      %{school: "Bradley University", mascot: "Braves"},
      %{school: "Brigham Young University", mascot: "Cougars"},
      %{school: "Brown University", mascot: "Bears"},
      %{school: "Bryant University", mascot: "Bulldogs"},
      %{school: "Bucknell University", mascot: "Bison"},
      %{school: "University at Buffalo", mascot: "Bulls"},
      %{school: "Butler University", mascot: "Bulldogs"},
      %{school: "University of California, Berkeley", mascot: "Golden Bears"},
      %{school: "University of California, Davis", mascot: "Aggies"},
      %{school: "University of California, Irvine", mascot: "Anteaters"},
      %{school: "University of California, Los Angeles", mascot: "Bruins"},
      %{school: "California Polytechnic State University", mascot: "Mustangs"},
      %{school: "University of California, Riverside", mascot: "Highlanders"},
      %{school: "University of California, Santa Barbara", mascot: "Gauchos"},
      %{school: "California State University, Bakersfield", mascot: "Roadrunners"},
      %{school: "California State University, Fresno", mascot: "Bulldogs"},
      %{school: "California State University, Fullerton", mascot: "Titans"},
      %{school: "California State University, Long Beach", mascot: "49ers"},
      %{school: "California State University, Northridge", mascot: "Matadors"},
      %{school: "California State University, Sacramento", mascot: "Hornets"},
      %{school: "Campbell University", mascot: "Fighting Camels and Lady Camels"},
      %{school: "Canisius College", mascot: "Golden Griffins"},
      %{school: "University of Central Arkansas", mascot: "Bears and Sugar Bears"},
      %{school: "Central Connecticut State University", mascot: "Blue Devils"},
      %{school: "University of Central Florida", mascot: "Knights"},
      %{school: "Central Michigan University", mascot: "Chippewas"},
      %{school: "College of Charleston", mascot: "Cougars"},
      %{school: "Charleston Southern University", mascot: "Buccaneers"},
      %{school: "Chicago State University", mascot: "Cougars"},
      %{school: "University of Cincinnati", mascot: "Bearcats"},
      %{school: "The Citadel", mascot: "Bulldogs"},
      %{school: "Clemson University", mascot: "Tigers"},
      %{school: "Cleveland State University", mascot: "Vikings"},
      %{school: "Coastal Carolina University", mascot: "Chanticleers"},
      %{school: "Colgate University", mascot: "Raiders"},
      %{school: "University of Colorado Boulder", mascot: "Buffaloes"},
      %{school: "Colorado State University", mascot: "Rams"},
      %{school: "Columbia University", mascot: "Lions"},
      %{school: "University of Connecticut (UConn)", mascot: "Huskies"},
      %{school: "Coppin State University", mascot: "Eagles"},
      %{school: "Cornell University", mascot: "Big Red"},
      %{school: "Creighton University", mascot: "Bluejays"},
      %{school: "Dartmouth College", mascot: "Big Green"},
      %{school: "Davidson College", mascot: "Wildcats"},
      %{school: "University of Dayton", mascot: "Flyers"},
      %{school: "University of Delaware", mascot: "Fightin' Blue Hens"},
      %{school: "Delaware State University", mascot: "Hornets and Lady Hornets"},
      %{school: "University of Denver", mascot: "Pioneers"},
      %{school: "DePaul University", mascot: "Blue Demons"},
      %{school: "University of Detroit Mercy", mascot: "Titans"},
      %{school: "Drake University", mascot: "Bulldogs"},
      %{school: "Drexel University", mascot: "Dragons"},
      %{school: "Duke University", mascot: "Blue Devils"},
      %{school: "Duquesne University", mascot: "Dukes"},
      %{school: "East Carolina University", mascot: "Pirates and Lady Pirates"},
      %{school: "East Tennessee State University", mascot: "Buccaneers and Lady Buccaneers"},
      %{school: "Eastern Illinois University", mascot: "Panthers"},
      %{school: "Eastern Kentucky University", mascot: "Colonels"},
      %{school: "Eastern Michigan University", mascot: "Eagles"},
      %{school: "Eastern Washington University", mascot: "Eagles"},
      %{school: "Elon University", mascot: "Phoenix"},
      %{school: "University of Evansville", mascot: "Purple Aces"},
      %{school: "Fairfield University", mascot: "Stags"},
      %{school: "Fairleigh Dickinson University", mascot: "Knights"},
      %{school: "University of Florida", mascot: "Gators"},
      %{school: "Florida A&M University", mascot: "Rattlers and Lady Rattlers"},
      %{school: "Florida Atlantic University", mascot: "Owls"},
      %{school: "Florida Gulf Coast University", mascot: "Eagles"},
      %{school: "Florida International University", mascot: "Panthers"},
      %{school: "Florida State University", mascot: "Seminoles"},
      %{school: "Fordham University", mascot: "Rams"},
      %{school: "Furman University", mascot: "Paladins and Lady Paladins"},
      %{school: "Gardner–Webb University", mascot: "Runnin' Bulldogs"},
      %{school: "George Mason University", mascot: "Patriots"},
      %{school: "George Washington University", mascot: "Colonials"},
      %{school: "Georgetown University", mascot: "Hoyas"},
      %{school: "University of Georgia", mascot: "Bulldogs and Lady Bulldogs"},
      %{school: "Georgia Institute of Technology", mascot: "Yellow Jackets"},
      %{school: "Georgia Southern University", mascot: "Eagles and Lady Eagles"},
      %{school: "Georgia State University", mascot: "Panthers"},
      %{school: "Gonzaga University", mascot: "Bulldogs"},
      %{school: "Grambling State University", mascot: "Tigers and Lady Tigers"},
      %{school: "Grand Canyon University", mascot: "Antelopes"},
      %{school: "Hampton University", mascot: "Pirates and Lady Pirates"},
      %{school: "University of Hartford", mascot: "Hawks"},
      %{school: "Harvard University", mascot: "Crimson"},
      %{school: "University of Hawaii at Manoa", mascot: "Rainbow Warriors and Rainbow Wahine"},
      %{school: "High Point University", mascot: "Panthers"},
      %{school: "Hofstra University", mascot: "Pride"},
      %{school: "College of the Holy Cross", mascot: "Crusaders"},
      %{school: "University of Houston", mascot: "Cougars"},
      %{school: "Houston Baptist University", mascot: "Huskies"},
      %{school: "Howard University", mascot: "Bison and Lady Bison"},
      %{school: "University of Idaho", mascot: "Vandals"},
      %{school: "Idaho State University", mascot: "Bengals"},
      %{school: "University of Illinois at Chicago", mascot: "Flames"},
      %{school: "Illinois State University", mascot: "Redbirds"},
      %{school: "University of Illinois at Urbana–Champaign", mascot: "Fighting Illini"},
      %{school: "University of the Incarnate Word", mascot: "Cardinals"},
      %{school: "Indiana University", mascot: "Hoosiers"},
      %{school: "Indiana State University", mascot: "Sycamores"},
      %{school: "Indiana University – Purdue University Indianapolis", mascot: "Jaguars"},
      %{school: "Iona College", mascot: "Gaels"},
      %{school: "University of Iowa", mascot: "Hawkeyes"},
      %{school: "Iowa State University", mascot: "Cyclones"},
      %{school: "Jackson State University", mascot: "Tigers and Lady Tigers"},
      %{school: "Jacksonville University", mascot: "Dolphins"},
      %{school: "Jacksonville State University", mascot: "Gamecocks"},
      %{school: "James Madison University", mascot: "Dukes"},
      %{school: "University of Kansas", mascot: "Jayhawks"},
      %{school: "Kansas State University", mascot: "Wildcats"},
      %{school: "Kennesaw State University", mascot: "Owls and Lady Owls"},
      %{school: "Kent State University", mascot: "Golden Flashes"},
      %{school: "University of Kentucky", mascot: "Wildcats"},
      %{school: "La Salle University", mascot: "Explorers"},
      %{school: "Lafayette College", mascot: "Leopards"},
      %{school: "Lamar University", mascot: "Cardinals and Lady Cardinals"},
      %{school: "Lehigh University", mascot: "Mountain Hawks"},
      %{school: "Liberty University", mascot: "Flames and Lady Flames"},
      %{school: "Lipscomb University", mascot: "Bisons and Lady Bisons"},
      %{school: "Long Island University", mascot: "Sharks"},
      %{school: "Longwood University", mascot: "Lancers"},
      %{school: "University of Louisiana at Lafayette", mascot: "Ragin' Cajuns"},
      %{school: "University of Louisiana at Monroe", mascot: "Warhawks"},
      %{school: "Louisiana State University", mascot: "Tigers and Lady Tigers"},
      %{school: "Louisiana Tech University", mascot: "Bulldogs and Lady Techsters"},
      %{school: "University of Louisville", mascot: "Cardinals"},
      %{school: "Loyola University Chicago", mascot: "Ramblers"},
      %{school: "Loyola University Maryland", mascot: "Greyhounds"},
      %{school: "Loyola Marymount University", mascot: "Lions"},
      %{school: "University of Maine", mascot: "Black Bears"},
      %{school: "Manhattan College", mascot: "Jaspers and Lady Jaspers"},
      %{school: "Marist College", mascot: "Red Foxes"},
      %{school: "Marquette University", mascot: "Golden Eagles"},
      %{school: "Marshall University", mascot: "Thundering Herd"},
      %{school: "University of Maryland, Baltimore County", mascot: "Retrievers"},
      %{school: "University of Maryland, College Park", mascot: "Terrapins"},
      %{school: "University of Maryland Eastern Shore", mascot: "Hawks and Lady Hawks"},
      %{school: "University of Massachusetts Amherst", mascot: "Minutemen and Minutewomen"},
      %{school: "University of Massachusetts Lowell", mascot: "River Hawks"},
      %{school: "McNeese State University", mascot: "Cowboys and Cowgirls"},
      %{school: "University of Memphis", mascot: "Tigers"},
      %{school: "Mercer University", mascot: "Bears"},
      %{school: "University of Miami", mascot: "Hurricanes"},
      %{school: "Miami University", mascot: "Redhawks"},
      %{school: "University of Michigan", mascot: "Wolverines"},
      %{school: "Michigan State University", mascot: "Spartans"},
      %{school: "Middle Tennessee State University", mascot: "Blue Raiders"},
      %{school: "University of Minnesota", mascot: "Golden Gophers"},
      %{school: "University of Mississippi", mascot: "Rebels"},
      %{school: "Mississippi State University", mascot: "Bulldogs"},
      %{school: "Mississippi Valley State University", mascot: "Delta Devils and Devilettes"},
      %{school: "University of Missouri", mascot: "Tigers"},
      %{school: "University of Missouri–Kansas City", mascot: "Kangaroos"},
      %{school: "Missouri State University", mascot: "Bears and Lady Bears"},
      %{school: "Monmouth University", mascot: "Hawks"},
      %{school: "University of Montana", mascot: "Grizzlies"},
      %{school: "Montana State University", mascot: "Bobcats"},
      %{school: "Morehead State University", mascot: "Eagles"},
      %{school: "Morgan State University", mascot: "Bears and Lady Bears"},
      %{school: "Mount St. Mary's University", mascot: "Mountaineers"},
      %{school: "Murray State University", mascot: "Racers"},
      %{school: "University of Nebraska–Lincoln", mascot: "Cornhuskers"},
      %{school: "University of Nebraska Omaha", mascot: "Mavericks"},
      %{school: "University of Nevada, Las Vegas", mascot: "Rebels"},
      %{school: "University of Nevada, Reno", mascot: "Wolf Pack"},
      %{school: "University of New Hampshire", mascot: "Wildcats"},
      %{school: "New Jersey Institute of Technology", mascot: "Highlanders"},
      %{school: "University of New Mexico", mascot: "Lobos"},
      %{school: "New Mexico State University", mascot: "Aggies"},
      %{school: "University of New Orleans", mascot: "Privateers"},
      %{school: "Niagara University", mascot: "Purple Eagles"},
      %{school: "Nicholls State University", mascot: "Colonels"},
      %{school: "Norfolk State University", mascot: "Spartans"},
      %{school: "North Carolina Agricultural and Technical State University", mascot: "Aggies"},
      %{school: "University of North Carolina at Asheville", mascot: "Bulldogs"},
      %{school: "North Carolina Central University", mascot: "Eagles"},
      %{school: "University of North Carolina at Chapel Hill", mascot: "Tar Heels"},
      %{school: "University of North Carolina at Charlotte", mascot: "49ers"},
      %{school: "University of North Carolina at Greensboro", mascot: "Spartans"},
      %{school: "North Carolina State University", mascot: "Wolfpack"},
      %{school: "University of North Carolina at Wilmington", mascot: "Seahawks"},
      %{school: "University of North Dakota", mascot: "Fighting Hawks"},
      %{school: "North Dakota State University", mascot: "Bison"},
      %{school: "University of North Florida", mascot: "Ospreys and Lady Ospreys"},
      %{school: "University of North Texas", mascot: "Mean Green"},
      %{school: "Northeastern University", mascot: "Huskies"},
      %{school: "Northern Arizona University", mascot: "Lumberjacks"},
      %{school: "University of Northern Colorado", mascot: "Bears"},
      %{school: "Northern Illinois University", mascot: "Huskies"},
      %{school: "University of Northern Iowa", mascot: "Panthers"},
      %{school: "Northern Kentucky University", mascot: "Norse"},
      %{school: "Northwestern University", mascot: "Wildcats"},
      %{school: "Northwestern State University", mascot: "Demons and Lady Demons"},
      %{school: "University of Notre Dame", mascot: "Fighting Irish"},
      %{school: "Oakland University", mascot: "Golden Grizzlies"},
      %{school: "Ohio University", mascot: "Bobcats"},
      %{school: "The Ohio State University", mascot: "Buckeyes"},
      %{school: "University of Oklahoma", mascot: "Sooners"},
      %{school: "Oklahoma State University–Stillwater", mascot: "Cowboys and Cowgirls"},
      %{school: "Old Dominion University", mascot: "Monarchs and Lady Monarchs"},
      %{school: "Oral Roberts University", mascot: "Golden Eagles"},
      %{school: "University of Oregon", mascot: "Ducks"},
      %{school: "Oregon State University", mascot: "Beavers"},
      %{school: "University of the Pacific", mascot: "Tigers"},
      %{school: "University of Pennsylvania", mascot: "Quakers"},
      %{school: "Pennsylvania State University", mascot: "Nittany Lions"},
      %{school: "Pepperdine University", mascot: "Waves"},
      %{school: "University of Pittsburgh", mascot: "Panthers"},
      %{school: "University of Portland", mascot: "Pilots"},
      %{school: "Portland State University", mascot: "Vikings"},
      %{school: "Prairie View A&M University", mascot: "Panthers and Lady Panthers"},
      %{school: "Presbyterian College", mascot: "Blue Hose"},
      %{school: "Princeton University", mascot: "Tigers"},
      %{school: "Providence College", mascot: "Friars"},
      %{school: "Purdue University", mascot: "Boilermakers"},
      %{school: "Purdue University Fort Wayne", mascot: "Mastodons"},
      %{school: "Quinnipiac University", mascot: "Bobcats"},
      %{school: "Radford University", mascot: "Highlanders"},
      %{school: "University of Rhode Island", mascot: "Rams"},
      %{school: "Rice University", mascot: "Owls"},
      %{school: "University of Richmond", mascot: "Spiders"},
      %{school: "Rider University", mascot: "Broncs"},
      %{school: "Robert Morris University", mascot: "Colonials"},
      %{school: "Rutgers University", mascot: "Scarlet Knights"},
      %{school: "Sacred Heart University", mascot: "Pioneers"},
      %{school: "St. Bonaventure University", mascot: "Bonnies"},
      %{school: "St. Francis College", mascot: "Terriers"},
      %{school: "Saint Francis University", mascot: "Red Flash"},
      %{school: "St. John's University", mascot: "Red Storm"},
      %{school: "Saint Joseph's University", mascot: "Hawks"},
      %{school: "Saint Louis University", mascot: "Billikens"},
      %{school: "Saint Mary's College of California", mascot: "Gaels"},
      %{school: "Saint Peter's University", mascot: "Peacocks and Peahens"},
      %{school: "Sam Houston State University", mascot: "Bearkats"},
      %{school: "Samford University", mascot: "Bulldogs"},
      %{school: "University of San Diego", mascot: "Toreros"},
      %{school: "San Diego State University", mascot: "Aztecs"},
      %{school: "University of San Francisco", mascot: "Dons"},
      %{school: "San Jose State University", mascot: "Spartans"},
      %{school: "Santa Clara University", mascot: "Broncos"},
      %{school: "Savannah State University", mascot: "Tigers and Lady Tigers"},
      %{school: "Seattle University", mascot: "Redhawks"},
      %{school: "Seton Hall University", mascot: "Pirates"},
      %{school: "Siena College", mascot: "Saints"},
      %{school: "University of South Alabama", mascot: "Jaguars"},
      %{school: "University of South Carolina", mascot: "Gamecocks"},
      %{school: "South Carolina State University", mascot: "Bulldogs and Lady Bulldogs"},
      %{school: "University of South Carolina Upstate", mascot: "Spartans"},
      %{school: "University of South Dakota", mascot: "Coyotes"},
      %{school: "South Dakota State University", mascot: "Jackrabbits"},
      %{school: "University of South Florida", mascot: "Bulls"},
      %{school: "Southeast Missouri State University", mascot: "Redhawks"},
      %{school: "Southeastern Louisiana University", mascot: "Lions and Lady Lions"},
      %{school: "Southern University", mascot: "Jaguars and Lady Jaguars"},
      %{school: "University of Southern California", mascot: "Trojans"},
      %{school: "Southern Illinois University Carbondale", mascot: "Salukis"},
      %{school: "Southern Illinois University Edwardsville", mascot: "Cougars"},
      %{school: "Southern Methodist University", mascot: "Mustangs"},
      %{school: "University of Southern Mississippi", mascot: "Golden Eagles and Lady Eagles"},
      %{school: "Southern Utah University", mascot: "Thunderbirds"},
      %{school: "Stanford University", mascot: "Cardinal"},
      %{school: "Stephen F. Austin State University", mascot: "Lumberjacks and Ladyjacks"},
      %{school: "Stetson University", mascot: "Hatters"},
      %{school: "Stony Brook University", mascot: "Seawolves"},
      %{school: "Syracuse University", mascot: "Orange"},
      %{school: "Temple University", mascot: "Owls"},
      %{school: "University of Tennessee", mascot: "Volunteers and Lady Vols"},
      %{school: "University of Tennessee at Chattanooga", mascot: "Mocs and Lady Mocs"},
      %{school: "University of Tennessee at Martin", mascot: "Skyhawks"},
      %{school: "Tennessee State University", mascot: "Tigers and Lady Tigers"},
      %{school: "Tennessee Technological University", mascot: "Golden Eagles"},
      %{school: "Texas A&M University", mascot: "Aggies"},
      %{school: "Texas A&M University–Corpus Christi", mascot: "Islanders"},
      %{school: "University of Texas at Arlington", mascot: "Mavericks"},
      %{school: "University of Texas at Austin", mascot: "Longhorns"},
      %{school: "Texas Christian University", mascot: "Horned Frogs and Lady Frogs"},
      %{school: "University of Texas at El Paso", mascot: "Miners"},
      %{school: "University of Texas Rio Grande Valley", mascot: "Vaqueros"},
      %{school: "University of Texas at San Antonio", mascot: "Roadrunners"},
      %{school: "Texas Southern University", mascot: "Tigers and Lady Tigers"},
      %{school: "Texas State University", mascot: "Bobcats"},
      %{school: "Texas Tech University", mascot: "Red Raiders"},
      %{school: "University of Toledo", mascot: "Rockets"},
      %{school: "Towson University", mascot: "Tigers"},
      %{school: "Troy University", mascot: "Trojans"},
      %{school: "Tulane University", mascot: "Green Wave"},
      %{school: "University of Tulsa", mascot: "Golden Hurricane"},
      %{school: "United States Air Force Academy (Air Force)", mascot: "Falcons"},
      %{school: "United States Military Academy (Army)", mascot: "Black Knights"},
      %{school: "United States Naval Academy (Navy)", mascot: "Midshipmen"},
      %{school: "University of Utah", mascot: "Utes"},
      %{school: "Utah State University", mascot: "Aggies"},
      %{school: "Utah Valley University", mascot: "Wolverines"},
      %{school: "Valparaiso University", mascot: "Crusaders"},
      %{school: "Vanderbilt University", mascot: "Commodores"},
      %{school: "University of Vermont", mascot: "Catamounts"},
      %{school: "Villanova University", mascot: "Wildcats"},
      %{school: "University of Virginia", mascot: "Cavaliers"},
      %{school: "Virginia Commonwealth University", mascot: "Rams"},
      %{school: "Virginia Military Institute", mascot: "Keydets"},
      %{school: "Virginia Tech", mascot: "Hokies"},
      %{school: "Wagner College", mascot: "Seahawks"},
      %{school: "Wake Forest University", mascot: "Demon Deacons"},
      %{school: "University of Washington", mascot: "Huskies"},
      %{school: "Washington State University", mascot: "Cougars"},
      %{school: "Weber State University", mascot: "Wildcats"},
      %{school: "West Virginia University", mascot: "Mountaineers"},
      %{school: "Western Carolina University", mascot: "Catamounts"},
      %{school: "Western Illinois University", mascot: "Leathernecks"},
      %{school: "Western Kentucky University", mascot: "Hilltoppers and Lady Toppers"},
      %{school: "Western Michigan University", mascot: "Broncos"},
      %{school: "Wichita State University", mascot: "Shockers"},
      %{school: "College of William & Mary", mascot: "Tribe"},
      %{school: "Winthrop University", mascot: "Eagles"},
      %{school: "University of Wisconsin–Green Bay", mascot: "Phoenix"},
      %{school: "University of Wisconsin–Madison", mascot: "Badgers"},
      %{school: "University of Wisconsin–Milwaukee", mascot: "Panthers"},
      %{school: "Wofford College", mascot: "Terriers"},
      %{school: "Wright State University", mascot: "Raiders"},
      %{school: "University of Wyoming", mascot: "Cowboys and Cowgirls"},
      %{school: "Xavier University", mascot: "Musketeers"},
      %{school: "Yale University", mascot: "Bulldogs"},
      %{school: "Youngstown State University", mascot: "Penguins"}
    ]
  end
end
